spring.application.name=salonpro-backend
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/salonpro
spring.datasource.username=salonpro_admin
spring.datasource.password=salonpro123!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jpa.show-sql=true